# Generated by Django 2.2 on 2021-04-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bday',
            field=models.DateField(default="2021-04-26"),
            preserve_default=False,
        ),
    ]
