# Generated by Django 2.2 on 2021-05-19 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_users_bday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='bday',
        ),
    ]
